-- models/staging/stg_menu.sql

{{ config(materialized='view') }}

SELECT
    MENU_ID,
    MENU_TYPE_ID,
    MENU_TYPE,
    TRUCK_BRAND_NAME,
    MENU_ITEM_ID,
    MENU_ITEM_NAME,
    ITEM_CATEGORY,
    ITEM_SUBCATEGORY,
    COST_OF_GOODS_USD,
    SALE_PRICE_USD,
    (SALE_PRICE_USD - COST_OF_GOODS_USD) AS PROFIT_USD
FROM SNOWFLAKE_LEARNING_DB.PAULA26_LOAD_SAMPLE_DATA_FROM_S3.MENU