{{ config(materialized='table') }}

SELECT
    s.SALE_ID,
    s.MENU_ITEM_ID,
    m.MENU_ITEM_NAME,
    s.SALE_DATE,
    s.QUANTITY,
    m.SALE_PRICE_USD,
    m.COST_OF_GOODS_USD,
    s.QUANTITY * m.SALE_PRICE_USD AS TOTAL_REVENUE,
    s.QUANTITY * (m.SALE_PRICE_USD - m.COST_OF_GOODS_USD) AS TOTAL_PROFIT
FROM SNOWFLAKE_LEARNING_DB.PAULA26_LOAD_SAMPLE_DATA_FROM_S3.DAILY_SALES s
JOIN {{ ref('stg_menu') }} m
    ON s.MENU_ITEM_ID = m.MENU_ITEM_ID
